version: '3.9'
services:
  nginx:
    ports:
      - "80:80"
  backend:
    build: 
      context: .
      args: 
        NODE_ENV: production
    volumes:
      - ./:/app
      - /app/node_modules
    # ports:
    #   - "4999:${PROD_PORT}"
    environment:
      - NODE_ENV=production
    command: node app.js