version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  backend:
    image: node-image
    build: .
    depends_on:
      - mongo 
    env_file:
      - ./.env
  mongo:
    image: mongo
    ports:
      # - 2717:27017
    volumes:
      - mongo_db:/data/db
  redis:
    image: redis
volumes:
  mongo_db:
